title: PacketGo 배포 이력
description: PRIBIT Connect 정규 버전 및 Hotfix 배포 관리
baseurl: "/packetgo-releases"
url: "https://zephylos.github.io"

collections:
  releases:
    output: true
    permalink: /releases/:name/

defaults:
  - scope:
      path: ""
      type: releases
    values:
      layout: release

plugins:
  - jekyll-feed
